### PR TITLE
Update to support the new version of Field Papers

### PR DESCRIPTION
**Pull request by sethfitz**
This switches from screen scraping bounds and URLs and guessing at zoom levels to fetching them from TileJSON that is now published as part of the new system.

@iandees what can we do to get a new version of the plugin published?

### CODE REVIEW

**Comment by sethfitz** [comment]
I've posted a JAR with these patches here:

https://github.com/fieldpapers/josm-fieldpapers/releases/download/v0.3.0/fieldpapers-0.3.0.jar

Put it in either `~/.josm/plugins` (Linux) or `~/Library/JOSM/plugins` (OS X).

**Comment by iandees** [comment]
I _think_ that if you update the JOSM plugin wiki with that new URL it should just magically work (as long as you incremented the version number in the manifest).

My local JOSM dev environment is broken for the near future.

**Comment by sethfitz** [comment]
Ok, I confirmed that `Plugin-Version` got updated to `v0.2.1-6-g4165022`.  (`g4165022` is the git revision, but I can't figure out where v0.2.1-6` comes from.  Any insight?

https://github.com/fieldpapers/josm-fieldpapers/releases/download/v0.3.0/fieldpapers-0.3.0.jar

**Comment by sethfitz** [comment]
Ah, figured it out.  It magically pulls that from the most recent tag.

**Pull request merged**
